$schema: "http://json-schema.org/draft-07/schema#"
title: "sample config"
type: object
additionalProperties: false

properties:
  namespace:
    type: string
    description: "Kubernetes namespace for all resources"
    default: "sample-ns"
  tlsIssuer:
    type: string
    description: "cert-manager ClusterIssuer name used by ingresses"
    default: "letsencrypt"

  tlsSecretName:
    type: string
    description: "TLS secret for ingress"
    default: "dev-certs-tls"
  
  app:
      type: object
      properties:
        name:   
          - type: string
          - default: "Acme"
        version:
          type: string
          description: "application version"
          default: "1.1.12"
        adminEmail:  { type: string, format: email, default: "admin@example.com" }
        flags:
          type: object
          properties:
            basicAuth: { type: boolean, default: false }
            sentryDsn: { type: string, default: "-" }
        enabledModules:
          type: array
          description: "enabledModules"
          items:
            type: string
          default:
            - dashboard
            - monitoring
            - interface

  copyrightCompanyName:
    type: string
    description: "Footer copyright company text"
    default: "Acme PVT LTD"

required:
  - namespace
  - app
